on:
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_RULES: "p/default"
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - id: json-out
      run: |
        semgrep ci --json --output trufflehog-findings.json || true
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-findings-json
        path: trufflehog-findings.json
  job2:
    runs-on: ubuntu-20.04
    needs: semgrep
    steps:
      - name: Download output
        uses: actions/download-artifact@v3
        with:
          name: trufflehog-findings-json
      - run : cat trufflehog-findings.json
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - run : aws s3 cp trufflehog-findings.json s3://semgrepci-findings-from-githubactions/
      - name: Invoke semgrep Lambda function
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: semgreppipeline-function
          Payload: '{ "filename": "trufflehog-findings.json", "repository-name": "${{ github.event.repository.name }}" }'
      
