on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '*/2 * * * *'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_RULES: "p/nginx custom-rule-XSS.yml"
    container:
      image: returntocorp/semgrep
      volumes:
      - ${{ github.workspace }}/.semgrep/:/github/home/.semgrep/
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
