on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '*/2 * * * *'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_RULES: "p/default"
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - id: junit-out
      run: |
        semgrep ci --junit-xml --output findings.xml || true
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: findings-junit-xml
        path: findings.xml
  job2:
    runs-on: ubuntu-20.04
    needs: semgrep
    steps:
      - name: Download output
        uses: actions/download-artifact@v3
        with:
          name: findings-junit-xml
      - run : cat findings-junit-xml
      
